cc_binary(
  name = "runner",
  srcs = [
      "main.cpp",
      "headers.h"
      ],
  deps = [
      "//shellsort:shellsort",
      "//quicksort:quicksort",
      "//mergesort:mergesort",
      ],
  data = [
      "//data:data",
      ],
)
  